### ISSUE TITLE
ModuleNotFoundError with pipx install

### ISSUE THREAD

**Issue by kevinbowen777** [davep/pispy#25]
I am getting a `ModuleNotFoundError` when trying to use PISpy using pipx to install the tool and am unable to run the application.

  - OS: Debian 12 stable
  - Python version: 3.12.3 (and 3.11.9)

Commands to reproduce:
  - `pipx install pispy-client`
  - `pipx install pispy-client --include-deps`
  - `pipx install pispy-client==0.5.0` (I have tried all release versions back to 0.1.0 with the same error output.)

Error message output:

```
$ pispy
Traceback (most recent call last):
  File "/home/kbowen/.local/bin/pispy", line 5, in <module>
    from pispy.__main__ import run
  File "/home/kbowen/.local/pipx/venvs/pispy-client/lib/python3.12/site-packages/pispy/__main__.py", line 14, in <module>
    from .app import PISpy
  File "/home/kbowen/.local/pipx/venvs/pispy-client/lib/python3.12/site-packages/pispy/app.py", line 11, in <module>
    from .widgets import PackageInformation
  File "/home/kbowen/.local/pipx/venvs/pispy-client/lib/python3.12/site-packages/pispy/widgets/__init__.py", line 5, in <module>
    from .package_information import PackageInformation
  File "/home/kbowen/.local/pipx/venvs/pispy-client/lib/python3.12/site-packages/pispy/widgets/package_information.py", line 12, in <module>
    from pkg_resources import parse_requirements
ModuleNotFoundError: No module named 'pkg_resources'
```

Please let me know if you need additional information.

**Comment by davep** [comment]
It's likely I've missed something off from setup.cfg when it comes to dependencies; although it's curious I've not seen any other reports of this and I don't see the same with fresh installations (pipx or homebrew) on macOS. 

I wonder also if https://stackoverflow.com/questions/61232326/python-pip-no-module-named-pkg-resources might be relevant here (searching the error does seem to turn up a few results with similar issues specifically on Debian).

**Comment by kevinbowen777** [comment]
Nice pointer!

After running `pipx install pispy-client`, I ran the command `pipx inject pispy-client setuptools` and the application appears to be functioning as expected.

**Comment by davep** [comment]
I suspect #27 will help out here.
